config/routes.rb
Rails.application.routes.draw do
  root :to => "wrestlers#index"
  get '/login' => 'session#new'        
  post '/login' => 'session#create' 
  delete '/login' => 'session#destroy'
  resources :wrestlers
  resources :promotions
  resources :users
  resources :teams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/promotion.rb
class Promotion < ApplicationRecord
    has_many :wrestlers
end

app/models/team.rb
class Team < ApplicationRecord
    belongs_to :user, :optional => true
    has_and_belongs_to_many :wrestlers
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
    has_many :teams
end

app/models/wrestler.rb
class Wrestler < ApplicationRecord
    has_and_belongs_to_many :teams, :optional => true
    belongs_to :promotion, :optional => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user

    private
    def fetch_user
        @current_user = User.find_by :id => session[:user_id]
        session[:user_id] = nil unless @current_user.present? # Log out non-existent users.
    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end

    def check_for_admin
        redirect_to login_path unless (@current_user.present? && @current_user.admin?)
    end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  def index
    @promotions = Promotion.all
  end

  def create
    promotion = Promotion.create promotion_params
    redirect_to promotion
  end

  def new
    @promotion = Promotion.new
  end

  def edit
    @promotion = Promotion.find params[:id]
  end

  def update
    promotion = Promotion.find params[:id]
    promotion.update promotion_params
    redirect_to promotion
  end

  def show
    @promotion = Promotion.find params[:id]
  end

  def destroy
    promotion = Promotion.find params[:id]
    promotion.destroy
    redirect_to promotions_path
  end

  private

  def promotion_params
    params.require(:promotion).permit(:abbrev, :logo, :name, :country, :year, :instagram)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create

    user = User.find_by :email => params[:email]
    #check if the hashed password matches
    if user.present? && user.authenticate(params[:password])
      # remember this user
      session[:user_id] = user.id
      redirect_to root_path
    else
      #todo: tell them they screwed up
      flash[:error]  = "Invalid username or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def new
    @team = Team.new
    @wrestlers = Wrestler.all
  end

  def create
    team = Team.create team_params
    team.user_id = @current_user.id
    redirect_to team
  end

  def index
    @teams = Team.all
  end

  def show
    @teams = Team.all
  end

  private

  def team_params
    params.require(:team).permit(:name, :wrestler_id => [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create    
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/wrestlers_controller.rb
class WrestlersController < ApplicationController
  def index
    @wrestlers = Wrestler.all
  end

  def show
    @wrestler = Wrestler.find params[:id]
  end

  def create
    wrestler = Wrestler.create wrestler_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      wrestler.image = req["public_id"]
      wrestler.save
    end
    redirect_to wrestler
  end

  def edit
    @wrestler = Wrestler.find params[:id]
  end

  def update
    wrestler = Wrestler.find params[:id]
    wrestler.update wrestler_params
    redirect_to wrestler
  end

  def new
    @wrestler = Wrestler.new
  end

  def destroy
    wrestler = Wrestler.find params[:id]
    wrestler.destroy
    redirect_to wrestlers_path
  end

  private

  def wrestler_params
    params.require(:wrestler).permit(:name, :image, :country, :height, :weight, :exp, :rating, :promotion_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wrestlers_helper.rb
module WrestlersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Suplex Slam Fantasy League</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= cloudinary_js_config %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

  </head>

  <body>

    <nav class="navbar navbar-expand-sm sticky-top bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/wrestlers"><%= image_tag 'ss_logo.png', :class => 'navbar-logo' %></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Wrestlers
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="/wrestlers">All Wrestlers</a></li>
                <% if @current_user.present? %>
                  <li><a class="dropdown-item" href="/wrestlers/new">New Wrestler</a></li>
                <% end %>
                <%= link_to "Random Wrestler", wrestler_path(Wrestler.order("RANDOM()").first), :class => "dropdown-item" %>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Promotions
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="/promotions">All Promotions</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Teams
              </a>
              <ul class="dropdown-menu">
                <a class="dropdown-item" href="/teams" class="nav-link">All Teams</a>
                <% if @current_user.present? %>
                  <a class="dropdown-item" href="/teams/new" class="nav-link">New Team</a>
                  <a class="dropdown-item" href="/teams/show" class="nav-link">My Teams</a>
                <% end %>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Account
              </a>
              <ul class="dropdown-menu">
                <% if @current_user.present? %>
                  <% if @current_user.admin? %>
                    <a class="dropdown-item" href="/users" class="nav-link">All Users</a>
                  <% end %>
                  <%= link_to "Log out #{ @current_user.email }", login_path, :class => 'dropdown-item', :method => :delete %>
                <% else %>
                  <a class="dropdown-item" href="/users/new" class="nav-link">Sign Up</a>
                  <a class="dropdown-item" href="/login" class="nav-link">Login</a>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

  </body>
</html>

app/views/promotions/_form.html.erb
<%= form_for @promotion do |f| %>
    <fieldset>
        <%= f.label :abbrev, "Abbreviation", :class => 'form-label'  %>
        <%= f.text_field :abbrev, :class => 'form-control'  %>

        <%= f.label :logo, :class => 'form-label'  %>
        <%= f.text_field :logo, :class => 'form-control' %>

        <%= f.label :name, :class => 'form-label'  %>
        <%= f.text_field :name, :class => 'form-control' %>

        <%= f.label :country, :class => 'form-label'  %>
        <%= f.text_field :country, :class => 'form-control' %>

        <%= f.label :year, :class => 'form-label'  %>
        <%= f.number_field :year, :class => 'form-control' %>

        <%= f.label :instagram, :class => 'form-label'  %>
        <%= f.url_field :instagram, :class => 'form-control' %>

        <%= f.submit :class => "btn btn-primary" %>

    </fieldset>
<% end %>

app/views/promotions/edit.html.erb
<h1>Edit Promotion</h1>
<h2><%= @promotion.name %></h2>
<%= render :partial => 'form' %>

app/views/promotions/index.html.erb
<h1>All Promotions</h1>

<% @promotions.each do |promotion| %>
    <%= link_to image_tag(promotion.logo, :class => 'logo'), promotion %>
<% end %>

app/views/promotions/new.html.erb
<h1>New Promotion</h1>

<%= render :partial => 'form' %>

app/views/promotions/show.html.erb
<h1><%= @promotion.abbrev %></h1>

<%= image_tag @promotion.logo, :class => 'logo_full' %>
<p>Name: <%= @promotion.name %></p>
<p>Country: <%= @promotion.country %></p>
<p>Year started: <%= @promotion.year %></p>
<p><%= link_to image_tag("insta.png", :class => 'insta'), @promotion.instagram, target: :_blank %></p>
<div>
    <h1>Wrestlers:<br></h1>
    <% @promotion.wrestlers.each do |wrestler| %>
        <%= link_to image_tag(wrestler.image, :class => 'thumb'), wrestler %>
    <% end %>
</div>
<%= link_to "Edit Promotion", edit_promotion_path %>
<%= link_to "Delete Promotion", promotion_path(@promotion), :method => :delete, :data => { :confirm => 'Are you sure?' } %>

app/views/session/new.html.erb
<h1>Login</h1>

<% if flash[:error].present? %>
    <h2><%= flash[:error] %></h2>
<% end %>
<%= form_tag login_path do %>
    <%= label_tag :email, nil, :class => 'form-label' %>
    <%= email_field_tag :email, nil, :class => 'form-control' %>

    <%= label_tag :password, nil, :class => 'form-label' %>
    <%= password_field_tag :password, nil, :class => 'form-control' %>
    
    <%= submit_tag "Sign in", :class => 'btn btn-danger btn-lg' %>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
    <p><%= user.email %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<% if @user.errors.any? %>
    <ol>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg  %></li>
        <% end %>
    </ol>
<% end %>


<%= form_for @user do |f| %>
    <%= f.label :email, :class => 'form-label' %>
    <%= f.email_field :email, :class => 'form-control' %>

    <%= f.label :password, :class => 'form-label' %>
    <%= f.password_field :password, :class => 'form-control' %>
    
    <%= f.label :password_confirmation, :class => 'form-label' %>
    <%= f.password_field :password_confirmation, :class => 'form-control' %>

    <%= f.submit "Sign up!", :class => "btn btn-primary" %>
<% end %>

app/views/wrestlers/_form.html.erb
<%= form_for(@wrestler, :html => {:multipart => true}) do |f| %>
    <fieldset>

        <%= f.label :name, :class => 'form-label' %>
        <%= f.text_field :name, :class => 'form-control' %>

        <%= f.label :image, :class => 'form-label' %>
        <%= f.text_field :image, :class => 'form-control' %>

        <%= f.label :country, :class => 'form-label' %>
        <%= f.text_field :country, :class => 'form-control' %>

        <%= f.label :height, :class => 'form-label' %>
        <%= f.number_field :height, :class => 'form-control' %>

        <%= f.label :weight, :class => 'form-label' %>
        <%= f.number_field :weight, :class => 'form-control' %>

        <%= f.label :exp, "Experience (years)", :class => 'form-label' %>
        <%= f.number_field :exp, :class => 'form-control' %>

        <%= f.label :rating, :class => 'form-label' %>
        <%= f.number_field :rating, step: 0.01, :class => 'form-control' %>

        <%= f.label :promotion_id, :class => 'form-label' %>
        <%= f.select :promotion_id, Promotion.pluck(:name, :id), :class => 'form-select', :id => "exampleFormControlSelect1" %>

        <%= f.submit :class => "btn btn-primary" %>

    </fieldset>
<% end %>

app/views/wrestlers/edit.html.erb
<h1>Edit Wrestler</h1>
<h2> <%= @wrestler.name %> </h2>

<%= render :partial => 'form' %>

app/views/wrestlers/index.html.erb
<h1>All Wrestlers</h1>

<% @wrestlers.each do |wrestler| %>
   <%= link_to image_tag(wrestler.image, :class => 'thumb'), wrestler if wrestler.image.present? %>
<% end %>

app/views/wrestlers/new.html.erb
<h1>New Wrestler</h1>

<%= render :partial => "form" %>

app/views/wrestlers/show.html.erb
<h1><%= @wrestler.name %></h1>

<%= image_tag @wrestler.image, :class => 'full' if @wrestler.image.present? %>

<div class="info">
    <p>Country: <%= @wrestler.country %></p>
    <p>Height: <%= @wrestler.height %> cm</p>
    <p>Weight: <%= @wrestler.weight %> kg</p>
    <p>Experience: <%= pluralize @wrestler.exp, 'year' %></p>
    <p>Promotion:<br><%= link_to image_tag(@wrestler.promotion.logo, :class => 'logo'), @wrestler.promotion %></p>
</div>

<%= link_to "Edit Wrestler", edit_wrestler_path(@wrestler) %>
<%= link_to "Delete Wrestler", wrestler_path(@wrestler), :method => :delete, :data => { :confirm => 'Are you sure?' } %>